Адаптивная сетка для страницы каталога
htmlacademy-adaptive/161553-pognali-21 pull request #12
Opened 2020-12-20 21:24 UTC by IreneMMM

2020-12-21 07:08 UTC, Dima-Dim requested changes

2020-12-21 07:08 UTC, Dima-Dim commented on source/less/blocks/country-filter.less
>    height: 39px;
Проблема при переполнении.

2020-12-21 07:08 UTC, Dima-Dim commented on source/catalog.html
> +      <ul class="page-header-social social__list">
Элемент `social__list` вне блока `social`

2020-12-21 07:08 UTC, Dima-Dim commented on source/catalog.html
> +                  <ul class="transport__list">
Элемент `transport__list` вне блока `transport`
И далее подобные ошибки.

2020-12-21 07:08 UTC, Dima-Dim commented on source/catalog.html
> +                    <input class="transport__icon-checkbox visually-hidden" type="checkbox" name="transport" value="plane" id="plane" checked="">
Duplicate ID и далее подобные ошибки.
https://validator.w3.org/nu/

2020-12-21 19:28 UTC, IreneMMM commented on source/catalog.html
> +      <ul class="page-header-social social__list">
исправила

2020-12-21 19:29 UTC, IreneMMM commented on source/catalog.html
> +                  <ul class="transport__list">
так есть же блок transport - 477 строка?

2020-12-21 19:30 UTC, IreneMMM commented on source/catalog.html
> +                    <input class="transport__icon-checkbox visually-hidden" type="checkbox" name="transport" value="plane" id="plane" checked="">
там вообще не должно быть input, там будут svg-иконки

2020-12-21 20:43 UTC, IreneMMM commented on source/catalog.html
> +                  <ul class="transport__list">
ниже нашла, исправила

2020-12-21 20:43 UTC, IreneMMM commented on source/catalog.html
> +              <p class="profile__interests-info">#ЗОЖ #ПП #Фитнес #пляж #авокадо #смузи</p>
на список да, но ссылки  - куда должны вести?

2020-12-21 21:29 UTC, IreneMMM commented on source/less/blocks/country-filter.less
>    height: 39px;
проблема в высоте, я так поняла, поставила min-height и padding

2020-12-22 07:03 UTC, Dima-Dim commented on source/catalog.html
> +              <p class="profile__interests-info">#ЗОЖ #ПП #Фитнес #пляж #авокадо #смузи</p>
Пока не куда, когда будут интегрировать решат :)

2020-12-22 07:10 UTC, Dima-Dim commented on source/catalog.html
> +                  <ul class="transport__list">
Да, сейчас стало лучше ;)

2020-12-22 07:10 UTC, Dima-Dim approved these changes

2020-12-22 07:10 UTC, merged