Стилизация главной страницы
htmlacademy-adaptive/161553-pognali-21 pull request #6
Opened 2020-11-25 01:06 UTC by IreneMMM

2020-11-25 05:04 UTC, Dima-Dim requested changes
companions_background_1.png - можно сделать на css.

companions_background_2.png, companions_background_3.png, header_mobile_background.png - почему png?

logo_mobile.svg - внутри не svg

traveller_mobile.png - похоже на svg.

2020-11-25 05:04 UTC, Dima-Dim commented on source/less/global/mixins.less
> +.visually-hidden {
Это отдельный блок.

2020-11-25 05:04 UTC, Dima-Dim commented on source/less/global/mixins.less
> +.button {
Это тоже похоже на отдельный блок.

2020-11-25 05:04 UTC, Dima-Dim commented on source/less/global/page.less
> +.page__body ul {
Не рекомендовал бы так делать.

2020-11-25 05:04 UTC, Dima-Dim commented on source/less/style.less
> +@import "global/variables.less";
Обычно ставятся в самое начало импортов, потому что могут быть использованы в любых других файлах

2020-11-25 19:34 UTC, IreneMMM commented on source/index.html
> +        <div class="registration__wrapper--text">
ok

2020-11-25 19:36 UTC, IreneMMM commented on source/index.html
> +        <div class="companions__wrapper--text">
ok

2020-11-25 19:37 UTC, IreneMMM commented on source/index.html
> +        <div class="directions__wrapper--text">
ok

2020-11-25 19:38 UTC, IreneMMM commented on source/index.html
> +        <div class="about__wrapper--text">
ok

2020-11-25 19:39 UTC, IreneMMM commented on source/index.html
> +        <div class="registration__wrapper--text">
ok

2020-11-25 19:43 UTC, IreneMMM commented on source/less/style.less
> +@import "global/variables.less";
Я так поняла речь о variables, исправила

2020-11-25 19:47 UTC, IreneMMM commented on source/less/global/page.less
> +.page__body ul {
убрала)

2020-11-25 19:55 UTC, IreneMMM commented on source/less/global/mixins.less
> +.button {
ok

2020-11-25 20:00 UTC, IreneMMM commented on source/less/global/mixins.less
> +.visually-hidden {
я переделала, но Вадим в лайве говорил, что можно visually-hidden засунуть в глобал, и еще так в демке(

2020-11-25 20:26 UTC, IreneMMM commented on source/less/blocks/main_nav.less
> +.site-list,
исправила

2020-11-25 20:30 UTC, IreneMMM commented on source/less/blocks/description.less
> +.action-list {
ok

2020-11-25 20:31 UTC, IreneMMM commented on source/index.html
> +        <div class="about__wrapper--text">
ok

2020-11-25 20:31 UTC, IreneMMM commented on source/index.html
> +        <div class="directions__wrapper--text">
ok

2020-11-25 20:31 UTC, IreneMMM commented on source/index.html
> +        <div class="companions__wrapper--text">
ok

2020-11-25 20:31 UTC, IreneMMM commented on source/index.html
> +        <div class="registration__wrapper--text">
ok

2020-11-25 22:07 UTC, IreneMMM commented on source/index.html
> +          <image id="image0" width="127" height="20" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAH8AAAAUCAYAAACkjuKKAAAFjUlEQVRoge2Ze4hXRRTHP6u59rAsy8xeaqFGZWmrpj3UwspCioge9iCyJ0GlkRWk
и правда, переделала на png

2020-11-26 05:26 UTC, Dima-Dim commented on source/less/global/mixins.less
> +.visually-hidden {
Попробовал бы Вадим с таким сходит на защиту :)

2020-11-26 13:06 UTC, IreneMMM commented on source/index.html
> +          <image id="image0" width="127" height="20" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAH8AAAAUCAYAAACkjuKKAAAFjUlEQVRoge2Ze4hXRRTHP6u59rAsy8xeaqFGZWmrpj3UwspCioge9iCyJ0GlkRWk
companions_background_1.png - переделала на css
companions_background_2.png, companions_background_3.png, header_mobile_background.png - если ставить jpg, остается задний фон белый, с png такого нет
traveller_mobile.png  - переделала на svg

2020-11-27 04:30 UTC, Dima-Dim commented on source/index.html
> +          <image id="image0" width="127" height="20" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAH8AAAAUCAYAAACkjuKKAAAFjUlEQVRoge2Ze4hXRRTHP6u59rAsy8xeaqFGZWmrpj3UwspCioge9iCyJ0GlkRWk
> companions_background_2.png, companions_background_3.png, header_mobile_background.png - если ставить jpg, остается задний фон белый, с png такого нет

Вижу только у companions_background_2.png скругления которые делаются через border-radius, остальные прямоугольники. Что за белый фон у них может быть?

2020-11-27 04:37 UTC, Dima-Dim commented
source/img/traveller_mobile.svg - всё ещё есть и внутри всё ещё не svg.

2020-11-27 04:38 UTC, Dima-Dim commented
Чтоб всё было единообразно рекомендую файл для блока page-footer называть page-footer.less, т.е. так же как и блок.

2020-11-27 16:08 UTC, IreneMMM commented on source/index.html
> +          <image id="image0" width="127" height="20" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAH8AAAAUCAYAAACkjuKKAAAFjUlEQVRoge2Ze4hXRRTHP6u59rAsy8xeaqFGZWmrpj3UwspCioge9iCyJ0GlkRWk
header_mobile_background - переделала на jpg, остальное оставила png как и говорили

2020-11-29 05:26 UTC, Dima-Dim approved these changes

2020-11-29 05:26 UTC, merged