Стилизация страницы формы
htmlacademy-adaptive/161553-pognali-21 pull request #7
Opened 2020-11-29 10:18 UTC by IreneMMM

2020-11-30 05:03 UTC, Dima-Dim requested changes

2020-11-30 05:03 UTC, Dima-Dim commented on source/less/blocks/companions-form.less
> +.companions-form-amount label,
Судя по названию файла, тут могут быть только селекторы блока `companions-form.less`

2020-11-30 05:03 UTC, Dima-Dim commented on source/less/blocks/user-tags.less
> +.user-transport__title {
Это какой-то другой блок.

2020-11-30 15:42 UTC, IreneMMM commented on source/less/blocks/companions-form.less
> +.companions-form-amount label,
ok

2020-11-30 15:42 UTC, IreneMMM commented on source/less/blocks/user-tags.less
> +.user-transport__title {
ok

2020-12-01 05:02 UTC, Dima-Dim requested changes

2020-12-01 05:02 UTC, Dima-Dim commented on source/less/blocks/companions-form.less
> +.companions-form-amount label {
Тогда и название файла `companions-form-amount` должно быть.

2020-12-01 05:24 UTC, IreneMMM commented on source/less/blocks/companions-form.less
> +.companions-form-amount label {
исправила)

2020-12-01 08:00 UTC, Dima-Dim approved these changes

2020-12-01 08:00 UTC, merged