Стилизация страницы каталога
htmlacademy-adaptive/161553-pognali-21 pull request #8
Opened 2020-12-01 19:15 UTC by IreneMMM

2020-12-02 10:34 UTC, Dima-Dim requested changes
`coutries__item` -> `countries__item` в catalog.html

2020-12-02 10:34 UTC, Dima-Dim commented on source/less/blocks/profile.less
> +.profile-catalog__button {
Выглядит как другой блок, возможно опечатка.

2020-12-02 10:34 UTC, Dima-Dim commented on source/catalog.html
> +        </li>@
@ - лишнее.

2020-12-02 17:17 UTC, IreneMMM commented on source/less/blocks/profile.less
> +.profile-catalog__button {
исправила

2020-12-02 17:17 UTC, IreneMMM commented on source/catalog.html
> +        </li>@
ok

2020-12-03 04:27 UTC, Dima-Dim approved these changes

2020-12-03 04:27 UTC, merged